# Generated by Django 3.1.4 on 2021-01-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='need_by_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m%d/'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
