# Generated by Django 3.1.4 on 2021-01-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210107_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='quantity',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
