# Generated by Django 3.1.4 on 2021-01-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210107_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='need_by_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
