# Generated by Django 3.1.4 on 2021-01-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210106_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
